save_path: "./data/ood"
carla_path: ""
carla_port: 2000
carla_host: "127.0.0.1"
carla_timeout: 10.0
episode_count: 10
tick_interval: 0.05
start_tick: 0
num_ego: 5
num_vehicles: 50
episode_length: 20
ood: ["static.prop.deer"]