save_path: "./data/train_aug"
carla_path: "../carla/carla13/CarlaUE4.sh"
carla_port: 2000
carla_host: "127.0.0.1"
carla_timeout: 30.0
episode_count: 13
tick_interval: 0.05
start_tick: -1
num_ego: 5
num_vehicles: 50
episode_length: 100
ood: ["static.prop.bear", "static.prop.cow", "static.prop.elephant", "static.prop.horse"]